import math
import torch
import os
import numpy as np
import random
import scipy

def _no_grad_trunc_normal_(tensor, mean, std, a, b):
    # Cut & paste from PyTorch official master until it's in a few official releases - RW
    # Method based on https://people.sc.fsu.edu/~jburkardt/presentations/truncated_normal.pdf
    def norm_cdf(x):
        # Computes standard normal cumulative distribution function
        return (1. + math.erf(x / math.sqrt(2.))) / 2.

    with torch.no_grad():
        # Values are generated by using a truncated uniform distribution and
        # then using the inverse CDF for the normal distribution.
        # Get upper and lower cdf values
        l = norm_cdf((a - mean) / std)
        u = norm_cdf((b - mean) / std)

        # Uniformly fill tensor with values from [l, u], then translate to
        # [2l-1, 2u-1].
        tensor.uniform_(2 * l - 1, 2 * u - 1)

        # Use inverse cdf transform for normal distribution to get truncated
        # standard normal
        tensor.erfinv_()

        # Transform to proper mean, std
        tensor.mul_(std * math.sqrt(2.))
        tensor.add_(mean)

        # Clamp to ensure it's in the proper range
        tensor.clamp_(min=a, max=b)
        return tensor


def trunc_normal_(tensor, mean=0., std=1., a=-2., b=2.):
    # type: (Tensor, float, float, float, float) -> Tensor
    return _no_grad_trunc_normal_(tensor, mean, std, a, b)


def apply_mask(mask, x):
    """
    :param x: tensor of shape [B (batch-size), N (num-patches), C, D (feature-dim)]
    :param mask: tensor [mN, mC] containing indices of patches in [N, C] to keep
    """
    B, N, C, D = x.shape
    if len(mask.shape) == 2:
        mN, mC = mask.shape

        mask_keep = mask.reshape((1, mN * mC, 1)).repeat((B, 1, D))
        masked_x = torch.gather(x.reshape((B, N * C, D)), dim=-2, index=mask_keep)
        masked_x = masked_x.contiguous().view((B, mN, mC, D))
    else:
        mN = mask.shape[0]

        mask_keep = mask.reshape((1, mN, 1)).repeat((B, 1, D))
        masked_x = torch.gather(x.reshape((B, N * C, D)), dim=-2, index=mask_keep)
    return masked_x


def apply_mask_t(mask_t, x):
    """
    :param x: tensor of shape [B (batch-size), N (num-patches), C, D (feature-dim)]
    :param mask: tensor [mN, mC] containing indices of patches in [N, C] to keep
    """
    B, N, D = x.shape
    mN = mask_t.shape[0]

    mask_keep = mask_t.reshape((1, mN, 1)).repeat((B, 1, D))
    masked_x = torch.gather(x, dim=1, index=mask_keep)
    return masked_x


def repeat_interleave_batch(x, B, repeat):
    N = len(x) // B
    x = torch.cat([
        torch.cat([x[i * B:(i + 1) * B] for _ in range(repeat)], dim=0)
        for i in range(N)
    ], dim=0)
    return x


# helper functions
def exists(val):
    return val is not None


# rotary embedding helper functions

def rotate_half(x):
    # x = rearrange(x, '... (d r) -> ... d r', r = 2)
    x = x.reshape((*x.shape[:-1], x.shape[-1] // 2, 2))
    x1, x2 = x.unbind(dim=-1)
    x = torch.stack((-x2, x1), dim=-1)
    # return rearrange(x, '... d r -> ... (d r)')
    return x.flatten(-2)


def apply_rotary_emb(freqs, t, start_index=0, scale=1.):
    freqs = freqs.to(t)
    rot_dim = freqs.shape[-1]
    end_index = start_index + rot_dim
    assert rot_dim <= t.shape[
        -1], f'feature dimension {t.shape[-1]} is not of sufficient size to rotate in all the positions {rot_dim}'
    t_left, t, t_right = t[..., :start_index], t[..., start_index:end_index], t[..., end_index:]
    t = (t * freqs.cos() * scale) + (rotate_half(t) * freqs.sin() * scale)
    return torch.cat((t_left, t, t_right), dim=-1)

# Sets random seeds across Python, NumPy, and PyTorch so results are reproducible
def seed_torch( seed ):
    random.seed( seed )
    os.environ[ "PYTHONHASHSEED" ] = str( seed ) # 为了禁止hash随机化，使得实验可复现
    np.random.seed( seed )
    torch.manual_seed( seed )
    torch.cuda.manual_seed( seed )
    torch.cuda.manual_seed_all( seed ) # if you are using multi-GPU.
    torch.backends.cudnn.benchmark = False
    torch.backends.cudnn.deterministic = True


def EA(x, new_R=None):
    # print(x.shape)
    '''
    The Eulidean space alignment approach for EEG data.

    Arg:
        x:The input data,shape of NxCxS
        new_R：The reference matrix.
    Return:
        The aligned data.
    '''

    xt = np.transpose(x, axes=(0, 2, 1))
    # print('xt shape:',xt.shape)
    E = np.matmul(x, xt)
    # print(E.shape)
    R = np.mean(E, axis=0)
    # print('R shape:',R.shape)

    R_mat = scipy.linalg.fractional_matrix_power(R, -0.5)
    new_x = np.einsum('n c s,r c -> n r s', x, R_mat)
    if new_R is None:
        return new_x

    new_x = np.einsum('n c s,r c -> n r s', new_x, scipy.linalg.fractional_matrix_power(new_R, 0.5))

    return new_x